trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install awscli
  displayName: 'Install AWS CLI'

- script: |
    export AWS_ACCESS_KEY_ID=$(AKIAXFYQZFAIWU5T22H6)
    export AWS_SECRET_ACCESS_KEY=$(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)
    aws configure set default.region us-east-1
  displayName: 'Configure AWS CLI'

- script: |
    ls -R $(Build.ArtifactStagingDirectory)
  displayName: 'List Files in Staging Directory'

- task: AWS-S3-Upload@0
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    BucketName: 'cpktnwt'
    DestinationFolder: '/'
    FilePattern: '**/*'
  displayName: 'Upload to S3'
