trigger:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install awscli
  displayName: 'Install AWS CLI'

- script: |
    aws configure set aws_access_key_id $(AKIAXFYQZFAIWU5T22H6)
    aws configure set aws_secret_access_key $(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)
    aws configure set default.region $(us-east-1)
  displayName: 'Configure AWS CLI'

- script: |
    aws s3 cp $(Build.SourcesDirectory)/pythonfile.py s3://cpktnwt/
  displayName: 'Copy Python file to S3'
